"""
Django settings for geodjango project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-fw@*-olpidf^0ooir34+lbq^hdn-w%q$00-!*)5o5r+lpkd63#',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').strip().lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]

# --- 1. GIS / GEODJANGO CONFIG ---
OSGEO4W_BIN = Path(os.environ.get("OSGEO4W_BIN", r"C:\OSGeo4W\bin"))
gdal_files = glob.glob(str(OSGEO4W_BIN / "gdal*.dll")) if OSGEO4W_BIN.exists() else []
GIS_ENABLED = bool(gdal_files)

if GIS_ENABLED:
    os.environ["PATH"] = str(OSGEO4W_BIN) + os.pathsep + os.environ["PATH"]
    GDAL_LIBRARY_PATH = gdal_files[0]
    geos_library = OSGEO4W_BIN / "geos_c.dll"
    if geos_library.exists():
        GEOS_LIBRARY_PATH = str(geos_library)
else:
    print(r"WARNING: GIS features are disabled because GDAL was not found.")

# --- 2. INSTALLED APPS ---
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt', 
    'channels',
    
    # Your Project Apps
    'accounts',
    'common',
]

if GIS_ENABLED:
    INSTALLED_APPS += [
        'tracking',
        'emergencies',
        'hospitals',
        'ambulances',
        'ai',
    ]

# --- 3. AUTH & USER CONFIG ---
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- 4. DATABASE CONFIG ---
USE_POSTGRES = os.environ.get("USE_POSTGRES", "").lower() in {"1", "true", "yes", "on"}

if USE_POSTGRES:
    default_engine = "django.contrib.gis.db.backends.postgis" if GIS_ENABLED else "django.db.backends.postgresql"
    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("POSTGRES_ENGINE", default_engine),
            "NAME": os.environ.get("POSTGRES_DB", "herd_db"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# --- 5. CHANNELS / ASGI ---
ASGI_APPLICATION = 'config.asgi.application'
WSGI_APPLICATION = 'config.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# --- 6. SMS CONFIG ---
SMS_PROVIDER = os.environ.get("SMS_PROVIDER", "console")
AFROMESSAGE_API_KEY = os.environ.get("AFROMESSAGE_API_KEY", "")
AFROMESSAGE_SENDER_ID = os.environ.get("AFROMESSAGE_SENDER_ID", "")
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")

# --- 7. MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Tell Django where your ASGI application is located
ASGI_APPLICATION = 'config.asgi.application'

# Configure the Channel Layer (uses Redis to pass messages between users)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv(
            'POSTGRES_ENGINE',
            'django.contrib.gis.db.backends.postgis',
        ),
        'NAME': os.getenv('POSTGRES_DB', 'herd_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'test'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if os.name == "nt":
    gdal_library_path = os.getenv("GDAL_LIBRARY_PATH")
    geos_library_path = os.getenv("GEOS_LIBRARY_PATH")

    default_gdal_path = Path(r"C:\OSGeo4W\bin\gdal312.dll")
    default_geos_path = Path(r"C:\OSGeo4W\bin\geos_c.dll")

    if not gdal_library_path and default_gdal_path.exists():
        gdal_library_path = str(default_gdal_path)
    if not geos_library_path and default_geos_path.exists():
        geos_library_path = str(default_geos_path)

    if gdal_library_path:
        GDAL_LIBRARY_PATH = gdal_library_path
    if geos_library_path:
        GEOS_LIBRARY_PATH = geos_library_path

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
